# 第09讲   numpy扩展包N维数组容器(Ndarray)


##  基础知识

NumPy的主要对象是同质**多维数组**。它是一个元素表（通常是数字），每个元素都是相同类型，通并过一组非负整数进行索引。在 NumPy 中，维度称为轴(axes)。

* ndarray.ndim
* ndarray.shape
* ndarray.size
* ndarray.dtype
* ndarray.itemsize
* ndarray.data

In [4]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
type(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15


numpy.ndarray

In [4]:
import numpy as np
a=np.random.randint(10,100,20)
print(a)
%whos

[31 91 86 70 95 90 18 18 22 47 45 18 10 22 20 94 48 33 21 29]
Variable   Type       Data/Info
-------------------------------
a          ndarray    20: 20 elems, type `int32`, 80 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [6]:
a=np.random.randint(10,100,20)
a.sort()
print(a)

[10 18 18 18 20 21 22 22 29 31 33 45 47 48 70 86 90 91 94 95]


In [8]:
a.sort(kind='heapsort')
a

array([10, 18, 18, 18, 20, 21, 22, 22, 29, 31, 33, 45, 47, 48, 70, 86, 90,
       91, 94, 95])

In [9]:
b=np.sort(a)
print(a,b)

[10 18 18 18 20 21 22 22 29 31 33 45 47 48 70 86 90 91 94 95] [10 18 18 18 20 21 22 22 29 31 33 45 47 48 70 86 90 91 94 95]


In [15]:
b=np.random.randint(1,50,24)
a=b.reshape(4,6)

a0=np.sort(a,axis=0) #竖排序
a1=np.sort(a,axis=1) #横排序
a2=np.sort(a,axis=None).reshape(4,6) #展平排序再折叠
print(a)
print(a0)
print(a1)
print(a2)

[[49 23 17 29  5 26]
 [47 15 24 40 29 49]
 [39 44 11 27  5 27]
 [25 23 16 40 24 18]]
[[25 15 11 27  5 18]
 [39 23 16 29  5 26]
 [47 23 17 40 24 27]
 [49 44 24 40 29 49]]
[[ 5 17 23 26 29 49]
 [15 24 29 40 47 49]
 [ 5 11 27 27 39 44]
 [16 18 23 24 25 40]]
[[ 5  5 11 15 16 17]
 [18 23 23 24 24 25]
 [26 27 27 29 29 39]
 [40 40 44 47 49 49]]


In [1]:
# help(np.sort)

In [47]:
help( np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [2]:
# help(np.argmin)