# 第16讲 数组的元素级运算(数组广播功能)

## Numpy广播计算

数组a与标量b的+,-,*,/,//(整数商除法),%(取余数除法),**(幂)运算

默认将标量b依据a行列数扩展为同结构的常数数组，然后再做对应位置的元素的+,-,*,/,//,%,**运算。

数组的函数运算：

利用数组的广播特性，数组内置的函数施加于数组的运算，自动分配到每个元素进行运算。例如sin(),sqrt(),sinc()等等。但外来函数施加于数组时，并不能把运算分配到每个元素，需要调用np.array(map(运算，数组名))来实现广播功能。

数组之间的+,-,*,/,//,%,**运算：
   要求参与运算的数组结构相同,至少行数或者列数相同，而且类型也有限制，例如字符数组不能与数值数组运算，等等。
   
##       数组op标量等价于所有数组元素op标量

```python 
import numpy as np;

a=np.array([[12,23],[34,45]]);
a+10,a-10,a*10,a/10,a//10,a%10运算结果分别是
```
```
a+10=> array([[22,33],[44,55]])
a-10=>array([[2,13],[24,35]])
a*10=>array([[120,230],[340,450]])
a/10=>array([[1.2,2.3],[3.4,4.5]])
a//10=>array([[1,2],[3,4]])
a%10=>array([[2,3],[4,5]])
```

In [3]:
import numpy as np;

a=np.array([[12,23],[34,45]]);
a+10,a-10,a*10,a/10,a//10,a%10

(array([[22, 33],
        [44, 55]]),
 array([[ 2, 13],
        [24, 35]]),
 array([[120, 230],
        [340, 450]]),
 array([[1.2, 2.3],
        [3.4, 4.5]]),
 array([[1, 2],
        [3, 4]], dtype=int32),
 array([[2, 3],
        [4, 5]], dtype=int32))

## 两个同结构数组的op运算等价于对应元素的op运算

## 单行数组与单列数组运算时，默认自动扩展后再运算

In [6]:
import numpy as np
a=np.array([[12,20,120]])
b=np.array([[3],[4]])
print(a)
print(b)
a+b,a-b,a*b,a/b,a//b,a%b,a**b

[[ 12  20 120]]
[[3]
 [4]]


(array([[ 15,  23, 123],
        [ 16,  24, 124]]),
 array([[  9,  17, 117],
        [  8,  16, 116]]),
 array([[ 36,  60, 360],
        [ 48,  80, 480]]),
 array([[ 4.        ,  6.66666667, 40.        ],
        [ 3.        ,  5.        , 30.        ]]),
 array([[ 4,  6, 40],
        [ 3,  5, 30]], dtype=int32),
 array([[0, 2, 0],
        [0, 0, 0]], dtype=int32),
 array([[     1728,      8000,   1728000],
        [    20736,    160000, 207360000]], dtype=int32))

## 等值扩列与等值扩行的巧妙实现


In [ ]:
import numpy as np
a=np.arange(16).reshape(1,16)
b=np.ones((16,1))
print()

不同结构的两个数组，结构满足条件时也可以默认扩展后参与运算。

**条件是：两个数组要么同行要么同列。**

例如2行3列与1行3列运算或与2行1列运算：
```
a+b=>array([[11,22,33],[41,52,63]])   a+c=>array([[14,24,34],[45,55,65]])
a-b=>array([[9,18,27],[39,48,57]])   a-c=>array([[6,16,26],[35,45,55]])
a*b=>array([[10,40,90],[40,100,180]])   a*c=>array([[40,80,120],[200,250,300]])
a//b=>array([[10,10,10],[40,25,20]])   a//c=>array([[2,5,7],[8,10,12]])
a%b=>array([[0,0,0],[0,0,0]])   a//c=>array([[2,0,2],[0,0,0]])
a**b=>array([[    10,    400,  27000],
       [    40,   2500, 216000]], dtype=int32)
a**c=>array([[    10000,    160000,    810000],
                         [102400000, 312500000, 777600000]], dtype=int32)
这种运算时自动扩展和对应元素运算的特性称为数组容器的广播特性。
```

In [11]:
import numpy as np;
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3]])
c=np.array([[4],[5]])
print(a)
print(b)
print(c)
print(a+b)
print(a+c)

[[10 20 30]
 [40 50 60]]
[[1 2 3]]
[[4]
 [5]]
[[11 22 33]
 [41 52 63]]
[[14 24 34]
 [45 55 65]]


In [12]:
(-1)**(1/3)

(0.5000000000000001+0.8660254037844386j)

In [24]:
a=((-1)**(1/3))**(np.exp(2j**np.pi*np.array([0,1,3])/3))
print(a.round(2))

print(np.round(a**3,3))

[ 0.5   +0.87j -0.6   -1.61j 63.68+200.62j]
[-1.00000000e+00+0.00000000e+00j  4.43700000e+00+2.38800000e+00j
 -7.43069441e+06-5.63341039e+06j]
