# 第17讲 数组的矩阵运算规则

数组a==> np.mat(a)==>矩阵a

In [1]:
import numpy as np
a=np.arange(16);
b=np.mat(a);
print('一维数组a=',a);
print('矩阵 b=',b)

一维数组a= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
矩阵 b= [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


矩阵运算：定义了矩阵运算规则的二维数组称为矩阵。无论数组还是矩阵，各行的列数必须相同，各列的行数必须相同。

## 矩阵运算(整体运算)（+，-，dot,inv,svd,eigvalues,...)

左列数与右行数相等的两个二维数组可以以矩阵规则做乘法即dot运算。数组参与矩阵乘法时，一维数组和单列二维数组都视为列向量。

行列数相等的数组（方阵）可以求逆（用于解线性代数方程组）、可以做奇异值分解、可以求特(本)征值及特(本)征向(矢)量。

* 科学研究最基本的问题之一是解多元线性代数方程组。

* 科学研究最基本的问题之二是解高阶线性常微分方程。高阶线性常微分方程可以转化为线性常微分方程组。线性常微分方程组又可以转化成矩阵的特征值问题。

因此，解线性常微分方程组和线性高阶微分方程的问题，都可以通过矩阵特征值问题求解来解决。
   
**科研的基本问题大多归结为解线性代数方程组和方阵的特征值问题。**



## 矩阵加减运算

两个矩阵结构相同，或者行数相同或者列数相同，就可以做加减运算，而且，运算时默认自动广播到两个结构相同为止，然后在对应位置元素之间的加减运算。在前面学习数组加减法时已经知晓。矩阵加法与数组加法完全相同。

一维数组和单列矩阵（数组）都称为列向量。单行矩阵（数组）称为行向量。

同结构列向量可以加减，同结构行向量可以加减。

行向量与列向量加减（因数组广播特性）将生成多行多列矩阵( 数组)。

矩阵可以加减常数，运算后结构不变。

两个既不同行也不同列的矩阵不能加减！

In [9]:
import numpy as np;
a=np.array([[1,2,3],[4,5,6]]);
b=np.array([[10,20,30]]);
c=np.array([[100],[200]])
print('a+b=',a+b);
print('b-a=',b-a);
print('a+1000=',a+1000);
print('b+c=',b+c)

a+b= [[11 22 33]
 [14 25 36]]
b-a= [[ 9 18 27]
 [ 6 15 24]]
a+1000= [[1001 1002 1003]
 [1004 1005 1006]]
b+c= [[110 120 130]
 [210 220 230]]


## 矩阵的行列式np.linalg.linalg.det 
## 矩阵的秩np.linalg.linalg.matrix_rank
## 矩阵的迹np.trace
## 方阵的行列式det

In [6]:

import numpy as np;
a=np.array([[2,1,3],[4,5,-10],[2,3,-4]])
print('a=',a);
print('矩阵的行列式det(a)=',np.linalg.linalg.det(a));

print('矩阵的迹trace(a)=',np.trace(a));

print('矩阵的秩matrix_rank(a)=',np.linalg.linalg.matrix_rank(a))


a= [[  2   1   3]
 [  4   5 -10]
 [  2   3  -4]]
矩阵的行列式det(a)= 22.000000000000004
矩阵的迹trace(a)= 3
矩阵的秩matrix_rank(a)= 3


## 两数组或矩阵的向量点积vdot

np.vdot(a,b)要求a和b的元数数量相同，先取a的复共轭，再做对应位置元素乘积，最后对所有乘积项求和，结果得到一个标量。
$$
np.vdot(a,b)

\sum_ka_k^*b_k
$$
或者说先将a和b都展平为一维数组，取a的复共轭，然后对应位置乘积，最后求和。例如

In [10]:
import numpy as np;
a=np.arange(48).reshape(4,3,4);
b=np.arange(10,481,10).reshape(4,2,2,3);
np.vdot(a,b),np.vdot(b,a)
c=np.arange(3,13)+1j*np.arange(13,3,-1);
np.vdot(c,c)

(1450+0j)

## dot是二维矩阵之间的乘法运算

如果a是m行n列矩阵(数组),b是p行q列矩阵(数组)，则仅当n=p时，两个个矩阵才能做点乘运算，其结果是一个m行q列的矩阵。即
换句话说，仅当前列数等于后行数的两个二维矩阵才能做点积运算，结果任然是一个二维矩阵。

有两层方括号的单行、单列矩阵(数组)的维数等于2.
有一层方括号的数组，可以扮演一个单列矩阵(数组)的角色。

In [16]:
a=np.array([[1,2],[3,4],[5,6]]);
b=np.array([[10,20,30,40,50],[12,23,34,45,56]]);
c=a.dot(b); 
d=np.array([[100],[200]]);
e=np.dot(a,d)
print('a=',a);
print('b=',b);
print('a.b=',c);
print('a.d=',e)
# a.b可以用a.dot(b)和np.dot(a,b)两种方式实现。

a= [[1 2]
 [3 4]
 [5 6]]
b= [[10 20 30 40 50]
 [12 23 34 45 56]]
a.b= [[ 34  66  98 130 162]
 [ 78 152 226 300 374]
 [122 238 354 470 586]]
a.d= [[ 500]
 [1100]
 [1700]]


## Python也定义了高维数组间的dot（乘积之和）运算。

a.b要求a的最后一维的大小等于b的倒数第二维的大小。

In [17]:
import numpy as np;
ar=np.array
a=ar(range(1,25)).reshape(2,3,4);
b=ar(range(25,1,-1)).reshape(2,4,3)
c=np.dot(a,b)
print('a=',a);
print('b=',b)
print('a.b=',c)

a= [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
b= [[[25 24 23]
  [22 21 20]
  [19 18 17]
  [16 15 14]]

 [[13 12 11]
  [10  9  8]
  [ 7  6  5]
  [ 4  3  2]]]
a.b= [[[[ 190  180  170]
   [  70   60   50]]

  [[ 518  492  466]
   [ 206  180  154]]

  [[ 846  804  762]
   [ 342  300  258]]]


 [[[1174 1116 1058]
   [ 478  420  362]]

  [[1502 1428 1354]
   [ 614  540  466]]

  [[1830 1740 1650]
   [ 750  660  570]]]]


## numpy定义了多种乘积再求和的运算

dot :左数组的最后一维与右数组的倒数第二维对应位置元素相乘再求和

inner:左数组的最后一维与右数组的最后一维对应位置元素相乘再求和

tensordot:两个数组关于指定轴axis的对应位置元素乘积再求和，即

np.dot(a,b)=np.tensordot(a,b,(-1,-2))# as=(-1,-2)如果b是一维的-2就是-1

np.inner(a,b)=np.tensordot(a,b,(-1,-1))#axis=(-1,-1)

可见三种乘积和运算都可以归结为tensordot(a,b,(n,m)),关键是两个数组参与乘积和运算的对应轴axis的大小必须相等才能配对相乘。

注意： dot,inner,tensordot 三个函数都在np名字空间的第一层。

## 数组的外积np.multiply.outer()

两个一维数组的外积是一个二维数组。例如

In [19]:
import numpy as np;
a=np.array([1,2,3]);
b=np.array([2,3,4]);
c=np.multiply.outer(a,b);
d=np.multiply.outer(b,a);
print(c)
print(d)

array([[ 253,  374,  495],
       [ 506,  748,  990],
       [ 759, 1122, 1485],
       [1012, 1496, 1980]])

 n 维数组与m 维数组的外积(outer)给出一个 m+n 维数组。 
 
 外积结果的维数为m+n，而点积、内积、张量积的结果维数为m+n-2。
 
 例如 

In [23]:
a=ar([[1,2,3],[4,5,6],[7,8,9]]);
b=ar([[10,20,30,40,50],[70,80,90,100,110]]);
c=np.multiply.outer(a,b);
print(c)

[[[[ 10  20  30  40  50]
   [ 70  80  90 100 110]]

  [[ 20  40  60  80 100]
   [140 160 180 200 220]]

  [[ 30  60  90 120 150]
   [210 240 270 300 330]]]


 [[[ 40  80 120 160 200]
   [280 320 360 400 440]]

  [[ 50 100 150 200 250]
   [350 400 450 500 550]]

  [[ 60 120 180 240 300]
   [420 480 540 600 660]]]


 [[[ 70 140 210 280 350]
   [490 560 630 700 770]]

  [[ 80 160 240 320 400]
   [560 640 720 800 880]]

  [[ 90 180 270 360 450]
   [630 720 810 900 990]]]]
