# 第11讲 N维数组(ndarray)实例的reshape

In [2]:
import numpy as np
x=np.arange(100,200,1)
print(x)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


In [3]:
np.sqrt(x)

array([10.        , 10.04987562, 10.09950494, 10.14889157, 10.19803903,
       10.24695077, 10.29563014, 10.34408043, 10.39230485, 10.44030651,
       10.48808848, 10.53565375, 10.58300524, 10.63014581, 10.67707825,
       10.72380529, 10.77032961, 10.81665383, 10.86278049, 10.90871211,
       10.95445115, 11.        , 11.04536102, 11.09053651, 11.13552873,
       11.18033989, 11.22497216, 11.26942767, 11.3137085 , 11.35781669,
       11.40175425, 11.44552314, 11.48912529, 11.53256259, 11.5758369 ,
       11.61895004, 11.66190379, 11.70469991, 11.74734012, 11.78982612,
       11.83215957, 11.87434209, 11.91637529, 11.95826074, 12.        ,
       12.04159458, 12.08304597, 12.12435565, 12.16552506, 12.20655562,
       12.24744871, 12.28820573, 12.32882801, 12.36931688, 12.40967365,
       12.4498996 , 12.489996  , 12.52996409, 12.56980509, 12.60952021,
       12.64911064, 12.68857754, 12.72792206, 12.76714533, 12.80624847,
       12.84523258, 12.88409873, 12.92284798, 12.9614814 , 13.  

In [4]:
index=np.array([True,False]*50)
x[index]

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [5]:
x[0:50:2]

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148])

In [6]:
list(x).index(169),list(x).count(169)

(69, 1)

In [7]:
c = np.array([[1, 2, 3, 4],[ 5, 6, 7,8], [ 9, 10,11,12]])
print(c,c.shape)
c.shape=4,3
print(c)
c.shape=2,-1
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
d=c.reshape(6,2)
d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
import numpy as np
def search(v,error,*x):
    """Search V in * X on Error!
    e.g searcg(15,0.0001,*[13,14.99999999,17,230])
    """
    p=[]
    ct=0
    for i in range(len(x)):
        if np.abs(v-x[i])<error:
            p.append(i)
            ct+=1
    return ct,p


In [11]:
%whos
search(14.0,0.1,*[11,12,13.999,14,14.0001,15,-12,14,-16,14,100])

Variable   Type        Data/Info
--------------------------------
c          ndarray     2x6: 12 elems, type `int32`, 48 bytes
d          ndarray     6x2: 12 elems, type `int32`, 48 bytes
index      ndarray     100: 100 elems, type `bool`, 100 bytes
np         module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
search     function    <function search at 0x000001E17C282438>
x          ndarray     100: 100 elems, type `int32`, 400 bytes


(5, [2, 3, 4, 7, 9])

In [12]:
help(search)

Help on function search in module __main__:

search(v, error, *x)
    Search V in * X on Error!
    e.g searcg(15,0.0001,*[13,14.99999999,17,230])

