# 第12讲 访问数组元素的方法 

1.   数组整体被访问获参与运算，这是数组实例的最重要的特性。例如

In [1]:
import numpy as np;
x=np.arange(100,120,4);
print(x)#整体输出
np.sqrt(x)# 整体参与开放运算

[100 104 108 112 116]


array([10.        , 10.19803903, 10.39230485, 10.58300524, 10.77032961])

2.  数组的每个元素也可以被单独访问，例如

In [3]:
x[0],x[-1],x[3]

(100, 116, 112)

3. 数组元素也可以被切片，即有规律的抽取部分数组元素，例如 

In [ ]:
x[::2]

4. 如果希望确定数组中有无给定数据，可以调用列表的index函数，或者调用列表的count函数。例如

In [4]:
import numpy as np;
x=np.random.randint(100,5000,100000);
v=1234;
list(x).index(v),list(x).count(v) #v在x中首次出现的索引和出现失误总次数


(273, 25)

5. 自定义查找函数serch,可以从数据容器示例中以给定误差阈值查找指定数据v出现的位置p及次数ct。


In [21]:
import numpy as np
def search(v,error,*x):
    """
    search  v in the  x on error
    e.g    search(12, 1e-10, array([10,11,12,13,14,15,156,12,100]))
    """
    p=[]
    ct=0
    for i in range(len(x)):
        if np.abs(v-x[i])<error:
                  p.append(i)
                  ct+=1
    return ct,p

In [23]:
search(12,1e-10,*np.array([10,11,12,34,56,12,78,100,12,12]))

(4, [2, 5, 8, 9])

## 数组的布尔面具与数组元素的条件选取

利用布尔面具，可以从数组中选出需要的部分元素。
例如 从数组中选出索引为偶数的元素：

方法1：“手工”利构造布尔面具m,利用数组实例名[面具名]选出偶数索引的元素

In [30]:
import numpy as np;
x=np.arange(20);
m=np.zeros(len(x));
m2=np.ones(len(x)//2);
m[::2]=m2;
m=m.astype(bool)
x[m]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

方法2：快速构造布尔面具，利用数组实例名[面具名]选出偶数索引的元素

In [31]:
import numpy as np;
x=np.arange(20);
m=x%2==0; 
print(x[m])

[ 0  2  4  6  8 10 12 14 16 18]


从40个均匀分布的随机数中选出位于指定区间内的部分随机数：

In [32]:
import numpy as np;
num=np.random.uniform(0,1,100);
num

array([0.04197492, 0.97972464, 0.33842348, 0.40663384, 0.18663266,
       0.61182049, 0.2163726 , 0.20479317, 0.15242836, 0.1809454 ,
       0.41402852, 0.13779566, 0.62969691, 0.44663986, 0.07764552,
       0.82419269, 0.94078979, 0.20564076, 0.05618579, 0.63818607,
       0.45140126, 0.87661016, 0.99729184, 0.33878349, 0.4841706 ,
       0.1104945 , 0.02321871, 0.0796316 , 0.55985709, 0.24493716,
       0.74650776, 0.91330275, 0.02217366, 0.0058122 , 0.0744859 ,
       0.56610396, 0.41281226, 0.52647333, 0.8374859 , 0.04078616,
       0.90773388, 0.90473693, 0.60773514, 0.46850794, 0.83206998,
       0.30831548, 0.30499138, 0.12113268, 0.99461747, 0.09230082,
       0.36330236, 0.42406489, 0.88591493, 0.52309563, 0.89065786,
       0.26753568, 0.70910878, 0.59006531, 0.77718169, 0.56419132,
       0.03943047, 0.66942155, 0.33641573, 0.73994514, 0.91170988,
       0.39716574, 0.11273672, 0.09577374, 0.28234086, 0.28186268,
       0.92782562, 0.39913283, 0.60455683, 0.22246247, 0.82894