# 第19讲 矩阵特征值问题和奇异值分解

## 矩阵的特征值问题

对于n阶方阵A，如果存在列向量Vec[i]和标量l[i]，使得

A.Vec[i]=l[i]*Vec[i],   i=0,1,...n-1

即在n阶方阵变换下方向保持不变、长度可变的向量称为该方阵的特征向量。

称Vec[i]是矩阵A的第i个特征向量，称 l[i]是关联特征向量Vec[i]的特征值（即特征向量的放大因子）。

寻找矩阵全部特征值及其对应特征向量的问题称为特征值问题（或本征值问题）。特征方程还可以写成

     A.V=V.diag(l)  
     
  即   A.[Vec[0],Vec[1],...Vec[n-1]]=[Vec[0],Vec[1],...Vec[n-1]].diag(l)
  
其中矩阵V的第i列是矩阵A的第i个特征向量Vec[i]，对应l[i]。
方阵diag(l)主对角线上依次是特征值l[0],l[1]...l[n-1]，diag(l)的主对角线以外的元素全为0.

## 矩阵特征值及其特征向量求解eig

In [26]:
import numpy as np; # b.vec[i]=lamda[i]*vec[i]; 

b=np.array([[2,1,5],[3,-4,7],[11,-7,13]]);
print(b)
print(np.linalg.det(b).round(3))  #计算行列值

val,vec=np.linalg.eig(b);  #矩阵特征值和特征向量

print("lamda=",val.round(3));

print("vec[0],vec[1],vec[2]=",vec.round(3))

[[ 2  1  5]
 [ 3 -4  7]
 [11 -7 13]]
147.0
lamda= [14.627+0.j  -1.813+2.6j -1.813-2.6j]
vec[0],vec[1],vec[2]= [[ 0.367+0.j     0.613+0.j     0.613-0.j   ]
 [ 0.378+0.j     0.034+0.598j  0.034-0.598j]
 [ 0.85 +0.j    -0.475+0.199j -0.475-0.199j]]


In [27]:
D=np.diag(val);
er1=np.dot(b,vec)-np.dot(vec,D);
er=np.abs(er1).max();
print(er.round(6))

for i in range(3):
    er2=np.dot(b,vec[:,i])-val[i]*vec[:,i];
    er=np.abs(er2).max();
    print(er.round(6),end=",")

0.0
0.0,0.0,0.0,

## 对称方阵与反对称方阵特征向量的特点研究

*  对称方阵的特征向量集合是正交归一集合。特征值为实数。
* 反对称方阵的特征向量集合是归一集合，但不是正交集合。特征值为纯虚数。
* 一般方阵的特征向量集合既不是正交的，也不是归一的。特征值为复数。

In [29]:
bdc=(b+b.T)/2
print(bdc)
val,vec=np.linalg.eig(bdc); 
print("lamda=",val.round(3));

print("v[0],v[1],v[2]=\n",vec.round(3))

[[ 2.  2.  8.]
 [ 2. -4.  0.]
 [ 8.  0. 13.]]
lamda= [17.249 -1.133 -5.116]
v[0],v[1],v[2]=
 [[-0.469 -0.744  0.476]
 [-0.044 -0.519 -0.854]
 [-0.882  0.421 -0.21 ]]


一般方阵的特征向量集合既不是正交的，也不是归一的。特征值为复数。

In [38]:
import numpy as np 
ar=np.array;
nll=np.linalg.linalg

a=ar([[1,2,3,4],[5,6,7,8],[7,-5,3,-2],[-3,11,-12,50]]);

print('a=\n',a); 

print('det(a)=', nll.det(a))

l,v=nll.eig(a)

print('l=\n',l.round(4)); 
print('l.imag=\n',l.imag)
print('v=\n',v. round(4))

vtv=v.T.dot(v). round(4)
print('v.T.dot(v)=\n', vtv)

a=
 [[  1   2   3   4]
 [  5   6   7   8]
 [  7  -5   3  -2]
 [ -3  11 -12  50]]
det(a)= -4875.9999999999945
l=
 [52.2371+0.j      4.9055+4.6385j  4.9055-4.6385j -2.048 +0.j    ]
l.imag=
 [ 0.        4.638474 -4.638474  0.      ]
v=
 [[-0.0806+0.j     -0.2592-0.0865j -0.2592+0.0865j  0.6569+0.j    ]
 [-0.1715+0.j     -0.8425+0.j     -0.8425-0.j      0.3381+0.j    ]
 [ 0.0458+0.j      0.07  -0.3951j  0.07  +0.3951j -0.6486+0.j    ]
 [-0.9808+0.j      0.216 -0.0887j  0.216 +0.0887j -0.1831+0.j    ]]
v.T.dot(v)=
 [[ 1.    +0.j     -0.0433+0.0759j -0.0433-0.0759j  0.039 +0.j    ]
 [-0.0433+0.0759j  0.6571-0.0488j  1.    +0.j     -0.54  +0.2157j]
 [-0.0433-0.0759j  1.    +0.j      0.6571+0.0488j -0.54  -0.2157j]
 [ 0.039 +0.j     -0.54  +0.2157j -0.54  -0.2157j  1.    +0.j    ]]


## 矩阵函数f(A)=V.f(D).VI
满秩方阵存在特征值问题。n阶方阵有n个特征值和n个特征向量。满秩n阶方阵可以分解为
        
        A=V.D.VI,  Vi=np.linalg.linalg.inv(V),  D=np.diag(l)
        
其中VI是V的逆矩阵，即V.VI=VI.V=I(单位矩阵),D是特征值l构造的对角矩阵。特别矩阵A的p次幂为：

        Ap=V.Dp.VI      以至于    f(A)=V.f(D).VI=V.diag(f(l)).VI
        
其中D^p是特征值的p次幂构成的对角矩阵。矩阵A的函数f等于矩阵特征值对角阵的函数diag(f(l))再左乘V右乘VI。   

利用这一特性，可以计算出以方阵为自变量的各类矩阵函数，前提是，矩阵是满秩方阵，函数可以展开成收敛幂级数。

## 矩阵奇异值分解svd

不满秩的方阵称为奇异矩阵。奇异矩阵也可以分解为

         A=S.diag(v).D   s-1.A.d-1=diag(v)
         
v是矩阵的奇异值，S和D与A矩阵的阶数相等。注意s与d的点积S.D不等于单位矩阵。

In [41]:
import numpy as np;

A=np.array([[1,2,3],[4,5,6],[3,6,9]])

s,v,d=np.linalg.linalg.svd(A);

print('s=\n',s);
print('v=\n',v);
print('d=\n',d)


s=
 [[-2.54678171e-01  1.87454073e-01 -9.48683298e-01]
 [-5.92781826e-01 -8.05363090e-01  4.45954139e-16]
 [-7.64034512e-01  5.62362218e-01  3.16227766e-01]]
v=
 [1.46452146e+01 1.58672309e+00 9.74960837e-16]
d=
 [[-0.33580314 -0.55017784 -0.76455255]
 [-0.8488637  -0.17503621  0.49879128]
 [-0.40824829  0.81649658 -0.40824829]]


## 点积应用一例：向量集合的正交归一化

线性独立向量集合v=[v0,v1,...vn-1]转化为正交归一向量集合u的算法为：


其中(uj*.vk)=dot(uk*,vk)是两向量的点积运算。

正交归一化需要的Python程序orth.py内容如下：

In [ ]:
    def orth(v):
    """
    v is a nonorthogonal set of vectors.
    v is a square matrix.
    Schmidt projection algorithm is used
       to normalize v into vector set u. 
    """
    import numpy as np;
    
    u=v.copy()
    r,n=v.shape
    
    us0[:,0].conjugate().dot(u[:,0]).real
    
    u[:,0]/=np.sqrt(us0)
    
    for i in range(1,n):
            for j in range(i):
                uv=u[:,j].conjugate().dot(v[:,i]); 
                u[:,i]-=uv*u[:,j]
            
            uin=u[:,i].conjugate().dot(u[:,i]).real
            
            u[:,i]/=np.sqrt(uin)
    
    udu=u.conjugate().T.dot(u)
    print('uTu=\n',udu.round(4))
    return u
