# 第14讲  数组运算(续)
## ——数组的平均值、方差、标准差、绝对值、四舍五入、类型转换、数制转换、转置、共轭、翻转

# 数组运算

* 平均值mean()
* 方差var()
* 标准差std()
* 绝对值abs()
* 四舍五入round()

* 类型转换astype
* 数制转换
* 转置
* 共轭
* 翻转

## 数组的均值mean()
均值： 指定数组的全部或部分元数求和后再除以元数个数。例如
一维数组的全局均值ar.mean()：

In [9]:
import numpy as np;
ar=np.random.randint(4,11,12);
av=ar.mean();print(ar,av)

[ 6  5 10  6  9  9 10 10  8  4  8  6] 7.583333333333333


二维数组的列向均值br.mean(axis=0)，行向均值br.mean(axis=1)，全局均值br.mean()

In [8]:
br=np.random.randint(4,11,(3,4));
print(br);
print(br.mean(axis=0));
print(br.mean(axis=1));
print(br.mean())

[[ 8  9  5  4]
 [ 8 10  9  6]
 [ 7  4  8 10]]
[7.66666667 7.66666667 7.33333333 6.66666667]
[6.5  8.25 7.25]
7.333333333333333


# 数组的方差var()和标准差std()

数组指定范围的元数求方差：每个元素与均值的差值平方求和再出元素个数。

例如: 二维数组的全局方差a.var()、列向方差a.var(axis=0)、行向方差a.var(axis=1)：


In [3]:
import numpy as np; 
a=np.arange(2,14).reshape(3,4);
print(a);
print(a.var());
print(a.var(axis=0));
print(a.var(axis=1))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]


二维数组的全局标准差a.std()、列向标准差a.std(axis=0)、行向标准差a.std(axis=1)：

In [4]:
print(a.std());print(a.std(axis=0));print(a.std(axis=1))

3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]


数组的绝对值abs、四舍五入round、类型转换 a.astype()

np.abs(Q)绝对值，np.round(Q,2)四舍五入保留两位小数，Q.astype(int8)转换为8bit 整数，Q.astype(np.uint8)转换为无符号8bit 整数。


In [ ]:
import numpy as np;Q=np.random.uniform(-10,10,10);print(Q)
print(np.abs(Q));print(np.round(Q,2));print(Q.astype(int8));print(Q.astype(np.uint8))


### 复数数组的共轭运算conjugate

In [1]:
import numpy as np;
c=np.arange(1,5)+np.arange(5,1,-1)*1j;
print(c)
d=c.reshape(2,2);
e=d.conjugate()
print('d=',d);
print('e=',e);
print('d+e=',(d+e).real)

[1.+5.j 2.+4.j 3.+3.j 4.+2.j]
d= [[1.+5.j 2.+4.j]
 [3.+3.j 4.+2.j]]
e= [[1.-5.j 2.-4.j]
 [3.-3.j 4.-2.j]]
d+e= [[2. 4.]
 [6. 8.]]


## 二维数组转置(a.T)

In [6]:
import numpy as np;
w=np.arange(12).reshape(3,4);
print('w=',w);
print('w.T=',w.T)
#一维数组需要先扩展为2维数组才能转置。例如
m=np.array([10,20,30]);
n=np.expand_dims(m,axis=0);
print((m.ndim,n.ndim,n.T.ndim)) #运行给出 (1, 2, 2)

w= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
w.T= [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(1, 2, 2)


# 数组的数制转换（hex(),oct(),bin()）

In [7]:
#实数的十六进制表示
import numpy as np;

P=np.array([10,12.5,-45]); 
list(map(float.hex,P))

# 整数的十六进制、八进制、二进制表示

w=np.array([7,15,23,171]);
np.array(list(map(hex,w)))
Q=np.array([10,12,14,16]);list(map(oct,Q))
L=np.array([1,2,8,16,32,64,128,256]);list(map(bin,L))


['0b1',
 '0b10',
 '0b1000',
 '0b10000',
 '0b100000',
 '0b1000000',
 '0b10000000',
 '0b100000000']